### ISSUE TITLE
Not working on ST3

### ISSUE THREAD

**Issue by LeonardoGentile** [markashleybell/ExpandTabsOnLoad#1]
Thanks  I've been looking for something like this for a long time!
The problem is that is seems not to work on st3. I haven't tested it on st2 tough

**Comment by markashleybell** [comment]
Ah! I haven't tested on ST3, as it didn't exist when I wrote this and I never upgraded. I will take a look ASAP though, would be good to get it working in both.

**Comment by ugiacoman** [comment]
Fixed if you want to use for ST3 3a7d7943c63cdade01bb46415722f0a5348a32b5

Also if you'd rather have the script run on saving the file change: 

``` python
def on-load
```

to

``` python
def on_pre_save
```
